version: '3.8'

services:
  # Database service (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: sentiment_db_fixed
    environment:
      POSTGRES_USER: ${DB_USER:-sentiment_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sentiment_password}
      POSTGRES_DB: ${DB_NAME:-sentiment_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data_fixed:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./init_scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-sentiment_user} -d ${DB_NAME:-sentiment_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

  # Redis service (Task queue and caching)
  redis:
    image: redis:7-alpine
    container_name: sentiment_redis_fixed
    command: redis-server --requirepass ${REDIS_PASSWORD:-sentiment_redis} --appendonly yes
    volumes:
      - redis_data_fixed:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-sentiment_redis}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

  # Fixed Model Service (VADER + HuggingFace with proper fallback)
  model-service-fixed:
    build:
      context: .
      dockerfile: Dockerfile.model-service-fixed
    container_name: model_service_fixed
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - MODEL_CACHE_DIR=/app/models
      - NLTK_DATA=/app/nltk_data
      - PYTHONPATH=/app
    volumes:
      - model_cache_fixed:/app/models
      - nltk_data_fixed:/app/nltk_data
      - ./logs:/app/logs
    ports:
      - "${MODEL_SERVICE_PORT:-8081}:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

  # Worker Scraper Service (Reddit data collection)
  worker-scraper-service:
    build:
      context: .
      dockerfile: Dockerfile.worker-scraper-service
    container_name: worker_scraper_service_fixed
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-sentiment_user}
      - DB_PASSWORD=${DB_PASSWORD:-sentiment_password}
      - DB_NAME=${DB_NAME:-sentiment_db}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-sentiment_redis}
      - MODEL_SERVICE_URL=http://model-service-fixed:8081
      - HOST=0.0.0.0
      - PORT=8082
      - PYTHONPATH=/app
      # Reddit API credentials
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT:-UCLA_STATS418_Sentiment_Analysis}
    volumes:
      - worker_data_fixed:/app/worker/data
      - ./logs:/app/worker/logs
    ports:
      - "${WORKER_PORT:-8082}:8082"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

  # Gateway API Service (Main orchestration service)
  gateway-api-service:
    build:
      context: .
      dockerfile: Dockerfile.gateway-api-service
    container_name: gateway_api_service_fixed
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-sentiment_user}
      - DB_PASSWORD=${DB_PASSWORD:-sentiment_password}
      - DB_NAME=${DB_NAME:-sentiment_db}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-sentiment_redis}
      - MODEL_SERVICE_URL=http://model-service-fixed:8081
      - WORKER_API_URL=http://worker-scraper-service:8082
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - POSTGRES_MAX_RETRY=5
      - POSTGRES_RETRY_INTERVAL=5
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      model-service-fixed:
        condition: service_healthy
      worker-scraper-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

  # Dashboard Service (Streamlit web interface)
  dashboard-service:
    build:
      context: .
      dockerfile: Dockerfile.dashboard-service
    container_name: dashboard_service_fixed
    environment:
      - API_URL=http://gateway-api-service:8080
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-sentiment_user}
      - DB_PASSWORD=${DB_PASSWORD:-sentiment_password}
      - DB_NAME=${DB_NAME:-sentiment_db}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-sentiment_redis}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - streamlit_data_fixed:/tmp/streamlit
    ports:
      - "${DASHBOARD_PORT:-8501}:8501"
    depends_on:
      gateway-api-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped
    networks:
      - sentiment_network_fixed

# Networks
networks:
  sentiment_network_fixed:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

# Volumes
volumes:
  postgres_data_fixed:
    driver: local
  redis_data_fixed:
    driver: local
  model_cache_fixed:
    driver: local
  nltk_data_fixed:
    driver: local
  worker_data_fixed:
    driver: local
  streamlit_data_fixed:
    driver: local
